FROM oven/bun:1

WORKDIR /app

COPY package.json bun.lock ./

RUN bun install --frozen-lockfile

COPY . .

RUN bun run build-storybook

RUN bun install -g http-server

EXPOSE 6006

CMD ["http-server", "storybook-static", "-p", "6006", "-d", "false"]
