/**
 * This file implements a catch-all route that renders the user-facing pages
 * generated by Puck. For any route visited (with exception of other hardcoded
 * pages in /app), it will check your database (via `getPage`) for a Puck page
 * and render it using <Render>.
 *
 * All routes produced by this page are statically rendered using incremental
 * static site generation. After the first visit, the page will be cached as
 * a static file. Subsequent visits will receive the cache. Publishing a page
 * will invalidate the cache as the page is written in /api/puck/route.ts
 */


import PageRender from "@components/PageRender";
import { footerConfig } from "@config/footer.config";
import { pageConfig } from "@config/page.config";
import { getFooter, getNavbar, getPage } from "@lib/db/database";
import { Metadata } from "next";
import { notFound } from "next/navigation";

type Params = Promise<{ puckPath: string[] }>;

export async function generateMetadata({
  params,
}: {
  params: Params;
}): Promise<Metadata> {
  const { puckPath = [] } = await params;
  const path = `/${puckPath.join("/")}`;
  const page = await getPage(path);

  if (!page) {
    return {};
  }

  return {
    title: page.root.props?.title || "Pfadi Meilen Herrliberg",
  };
}

export default async function Page({ params }: { params: Params }) {
  const { puckPath = [] } = await params;
  const path = `/${puckPath.join("/")}`;
  const pageData = await getPage(path);

  if (!pageData) {
    return notFound();
  }

  const navbarData = await getNavbar();
  const footerData = await getFooter();

  return (
    <PageRender
      {...{
        navbarData,
        pageData,
        footerData,
        pageConfig,
        footerConfig,
      }}
    />
  );
}
